### ISSUE TITLE
Consistent naming

### ISSUE THREAD

**Issue by dslama** [wunderwiki/MW-extensions#1]
@louis-jackman 
TBD: Change all occurences of WikiPublisher to WonderWiki - or Change the name of the git hub repo to WikiPublisher, if this is too much effort.

**Comment by dslama** [comment]
Make Newsletter registration neutral, i.e. eliminate references to AIoT in the form

**Comment by louis-jackman** [comment]
I've changed the extension code to work with the new name, WunderWiki, and uploaded the changes to both sites.

Updated the documentation in the Wiki section to reflect the new changes as well.
